Update to 1.20.1
shedaniel/RoughlyEnoughResources pull request #10
Opened 2023-06-24 13:41 UTC by ThexXTURBOXx

Tested this in dev and production and everything seems to work fine

2023-07-02 00:52 UTC, sternschnaube commented
Thanks for the update 🥳

2023-07-24 05:37 UTC, shedaniel requested changes
95% of the changes are code style related, please do not do PRs like this.
I will see if I have time to minimise the diff, or this PR requires changes

2023-07-24 05:52 UTC, ThexXTURBOXx commented
As far as I can tell, most of the changes are actually real changes and the style changes only apply to two files. I will see in a few hours if I have enough time to fix those. Otherwise I don't see what should be wrong

2023-07-25 03:11 UTC, shedaniel commented
I appreciate this pull request, but merging this makes it hard to cherry pick stuff over and maintain stuff in the future. You changed indents in many files, messed up imports, added random line breaks.

After removing unrelated changes, the diff changed from **+314 −237** to **+59 −58**, there is no way that wasn't significant.

2023-07-25 03:20 UTC, shedaniel approved these changes

2023-07-25 03:21 UTC, merged